name: calculator
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  args: ^2.5.0
  characters: ^1.3.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
     
